trigger:
- master

variables:
  buildConfiguration: 'Release'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Premium with MSDN(3971beac-e624-4a42-8cf9-a86e4d6376dd)'
    appType: 'webApp'
    appName: 'testAzurePipelinesBendando'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

